### ISSUE TITLE
g.Tec\g.HIamp runtime error

### ISSUE THREAD

**Issue by dmedine** [sccn/lsl_archived#112]
This is the same issue as #110 
![ghiamp_error](https://cloud.githubusercontent.com/assets/3613166/14443104/08bca958-fff2-11e5-9a5b-7b716739b703.png)

**Comment by chkothe** [comment]
This one needs the gHIamp.dll -- I don't seem to have it at hand here,
perhaps there was a license issue. Curiously I'm getting a more informative
error message that names the dll, weird...

Christian

**Comment by dmedine** [comment]
Yeah, I can't seem to find it in any of my old folders either. I checked the website and the software/drivers download page was beyond my permissions to access. I'll leave this open until we can hunt down the library but this is clearly what is missing.

**Comment by cboulay** [comment]
This issue was moved to labstreaminglayer/App-g.Tec#5
