### ISSUE TITLE
How to read multiple types at the same time?

### ISSUE THREAD

**Issue by Jianbin-IBM** [sccn/lsl_archived#179]
Hi, in my current stream, I have EEG, AUX and so on. May I know how to use python to read more than 1 type at the same? Current example in "ReceiveData.py" seems only support read 1 type.
streams = resolve_stream('type', 'EEG')
Thanks very much!

**Comment by cboulay** [comment]
The 'type' parameter is just an identifier, it doesn't have any special meaning. You can give it an arbitrary type name when you create the outlet and you can use that made up name when trying to resolve it. There may be some signal processing tools that treat streams with specific types in specific ways (e.g. eeglab import tool looks for stream of type Markers), but labstreaminglayer itself doesn't care.
