### ISSUE TITLE
32 channels g.tec APP

### ISSUE THREAD

**Issue by JARS29** [sccn/lsl_archived#192]
Hi!

I'm trying to collect EEG data using g.tec amp 32 channels through LSL. I opened the APP for g.tec, where  16 channels are setup up for default.  When I try to modify the number of channels (including the channel labels) it is not possible (the GUI object for that "number of channels" is blocked ). See the picture:

![image](https://cloud.githubusercontent.com/assets/23078352/25204222/b984c7b2-255c-11e7-89b3-a975b81cdc6f.png)

I tried to modify the file "gUSBamp_config.cfg" adding the channel labels and the number of channels, but when i run the app appear the labels but the object remains blocked with the number 16.

can anyone tell me if with the current LSL APP is possible recording 32 channels?

Now, I'm making a script for collecting the data from g.tec and push it in the LSL. (an update of it coming soon). 

Really, i will appreciate a lot your help, I don't want spend more time on it.  

Thank you.

**Comment by dmedine** [comment]
I will have to check the code, but it appears that the app can only 
support 16 channels.

**Comment by cboulay** [comment]
I've created a new g.Tec/g.NEEDaccess application that can now support multiple g.USBamps in master/slave. There are some reasons why one might want to use the direct API instead of the server/client g.NEEDaccess API, so I don't consider this issue solved, but at least there is an alternative for now.

**Comment by tstenner** [comment]
@cboulay Is your gUSB.amp app ready so I can close this?

**Comment by cboulay** [comment]
Nope! There's still a buffer problem at high sampling rates. I haven't had time to get back to it recently. Feel free to move the issue to labstreaminglayer/App-g.Tec

**Comment by cboulay** [comment]
This issue was moved to labstreaminglayer/App-g.Tec#6
