### ISSUE TITLE
CMake build issues (Windows 10 x64)

### ISSUE THREAD

**Issue by mgrivich** [sccn/lsl_archived#241]
I am following the instructions at https://github.com/sccn/labstreaminglayer/blob/master/INSTALL.md (on Windows 10 x 64)

```
cd labstreaminglayer
mkdir build
cd build
cmake -DVARX=Y ../
```

I get

```
-- Linking LSL against: lslboost
-- Found Boost libraries:
-- Found target lsl in current build tree
-- Found target lsl in current build tree
CMake Error at Apps/LabRecorder/CMakeLists.txt:27 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "C:/nbs/external/labstreaminglayer-official-git/build/CMakeFiles/CMakeOutput.log".
See also "C:/nbs/external/labstreaminglayer-official-git/build/CMakeFiles/CMakeError.log".
```

It should be possible to build only the lsl library, without having QT installed. It should be possible to build only the lsl library, without any of the apps.

**Comment by cboulay** [comment]
When we asked @dmedine which apps should be built by default the answer was LabRecorder and XDFBrowser (turned on [here](https://github.com/sccn/labstreaminglayer/blob/master/Apps/CMakeLists.txt#L15-L19)). It is possible to build without them by passing the following argument to cmake: `-DLSLAPPS_LabRecorder=OFF -DLSLAPPS_XDFBrowser=OFF`.

We could make this a single argument by making it so cmake doesn't even traverse the Apps directory if something like `-DLSL_NOAPPS` is set. Is that preferable?

**Comment by mgrivich** [comment]
Yes. That is more intuitive and future proof.

**Comment by tstenner** [comment]
I'm thinking about reverting that change so no apps are built by default and improve the starting configuration somehow. Labrecorder requires Qt5 and Boost, XDFViewer isn't that useful for the average user and both might be irrelevant for users who just want the language bindings.

**Comment by dmedine** [comment]
I quite agree. I don't know why I thought that was a good idea at the 
time. In practice it feels totally wrong.

**Comment by mgrivich** [comment]
Ok. I agree.

**Comment by mgrivich** [comment]
Moving on (I've edited the title of the bug in increase the scope). I created a visual studio command prompt using the instructions at https://www.stevefenton.co.uk/2015/06/add-visual-studio-command-prompt-to-visual-studio-2015/ I then did: 

```
c:\nbs\external\labstreaminglayer-official-git\build>cmake --generator="Visual Studio 14 2015 Win64" -DVARX=Y -DLSLAPPS_LabRecorder=OFF -DLSLAPPS_XDFBrowser=OFF -DCMAKE_BUILD_TYPE=Release ../
c:\nbs\external\labstreaminglayer-official-git\build>cmake --build .
```
The LSL library built, but with a huge number of warnings. These should be either suppressed with compiler flags or fixed, depending on the warning. Boost warnings should certainly be suppressed with compiler flags. In addition, even though I specified Release and Win64, it built debug 32 (at least if the name of the dll can be trusted).

**Comment by cboulay** [comment]
I've never actually used cmake that way. I usually use cmake to configure the project then I open the project in Visual Studio. When doing it this way, I've found that the CMAKE_BUILD_TYPE argument has no effect on the project itself, because both Release and Debug build targets are configured and available in Visual Studio's target config. Maybe that argument needs to be passed to cmake when passing --build?

**Comment by cboulay** [comment]
Also, I've only ever used `-G "Visual Studio 14 2015 Win64"`, not `--generator=`. The `--generator=` is what needs to be passed to the python script, not cmake, I think.

**Comment by mgrivich** [comment]
Using -G instead of --generator fixed the 32/64 bit issues. It is still 
not apparent how to switch between debug and release with the build command.

**Comment by cboulay** [comment]
See my edits above.

**Comment by mgrivich** [comment]
cmake --build . --config Release worked. By the way, I know I'm being lazy, but I'm debugging your documentation as much as anything. As much as possible, we want the easily-accessible documentation to be copy-paste-run, as many of our users are not particularly experienced.

**Comment by cboulay** [comment]
I agree and I'm grateful for the effort.

**Comment by tstenner** [comment]
Windows builds are more complicated than I thought.
`build_windows.bat` in 77b67f58 should be a lot easier: it creates a build directory, asks for the compiler to use, mostly automatically detects Qt5, creates a Visual Studio project and builds redistributable binaries so the instructions should boil down to "Install, CMake and Visual Studio, launch `build_windows.bat` and everything should work".

**Comment by dmedine** [comment]
Getting back to the op, I am getting the same error that Matthew reports when trying to build LabRecorder using CMake. How does one overcome this error message apart from _not_ building LabRecorder (which is precisely what I wish to do)?

**Comment by tstenner** [comment]
The `Could not find a package configuration file provided by "Qt5"`-error?
The current master should detect the correct Qt folder under some circumstances, otherwise you'd need to set the correct folder with `-DQt5_DIR=C:/Qt/5.9.2/msvcxxxx_yy/lib/cmake/Qt5`. Capitalization matters in `Qt5_DIR` and the last `/lib/cmake/Qt5` part is needed instead of the general installation dir.

**Comment by dmedine** [comment]
Sorry, I didn't look at Matthew's post very carefully. I'm getting the error when it searches for LSL:
```
-- Trying to find package LSL
CMake Error at C:/Users/David.Medine/clean_lsl/lslboost_update/cmake/LSLAppBoilerplate.cmake:15 (find_package):
  By not providing "FindLSL.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "LSL", but
  CMake did not find one.

  Could not find a package configuration file provided by "LSL" with any of
  the following names:

    LSLConfig.cmake
    lsl-config.cmake

  Add the installation prefix of "LSL" to CMAKE_PREFIX_PATH or set "LSL_DIR"
  to a directory containing one of the above files.  If "LSL" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:14 (include)


-- Configuring incomplete, errors occurred!
See also "C:/Users/David.Medine/clean_lsl/lslboost_update/Apps/LabRecorder/CMakeFiles/CMakeOutput.log".
```

**Comment by tstenner** [comment]
From which folder are you calling CMake? I'm not sure how to get this error message - if you're building the whole tree, the `LSL` target should be there automatically, if not, it should give an error message about a missing `LSL_ROOT` before this one.

**Comment by dmedine** [comment]
I was calling from the LabRecorder folder. I specified the lsl_root as ../../. Also, this is from a clone of your lslboost_update fork. I had already build liblsl from the liblsl directory prior to running this. When I call build_windows.bat I get an lslboost_DIR and LSL_DIR not found errors.

When I run build_windows.bat from a clean clone of master and select the labrecorder box I get a Qt5_DIR not found error (presumably this is the same that Matthew encountered). 

It appears that this still needs a bit of work on Windows. Has anyone built an app using the cmake stuff on Windows yet? I am still unable to do so. I suspect there needs to be a whole bunch of if(WIN32) statements in the CMakeList files.

**Comment by tstenner** [comment]
Ah, I hadn't considered that. There's two ways to build an app:
- in-tree, i.e. launching CMake from the main folder. That way, CMake knows everything about the library (because it's building it at the same time). Since building the LSL library takes 1-2 minutes and has no further dependencies, it should be no big deal to build it alongside a single app.
- out of tree, i.e. only this single app. In this case, CMake needs to know where to find the library (.dll or .so), which compiler settings need to be considered etc. To do this, CMake generates a configuration file (`LSLConfig.cmake`) after building the library that gets 'installed' together with the library and the header files. `LSL_ROOT` tells where to find this configuration file.

Setting `LSL_ROOT` to the root folder for an out of tree build fails, because there's no built library (and therefore no library configuration).

**Comment by dmedine** [comment]
Thanks for the explanation. I had a feeling something was missing. Also, I found the magic words for Cmake to find Qt and Boost on Windows. Apparently setting the BOOST_ROOT env variable is not enough for cmake and the paths to the libraries and the headers need to be declared explicitly (I'm not the first person to encounter this on Windows: https://stackoverflow.com/questions/3808775/cmake-doesnt-find-boost). In the case of Qt, the qt folder has to be included in a cmake environment variable (https://stackoverflow.com/questions/15639781/how-to-find-qt5-cmake-module-on-windows). 

Fortunately, this can be done parametrically on the command line. This is the command I am running from the LabRecorder folder:

> cmake -DCMAKE_PREFIX_PATH=C:\Qt-VS2012_x64\Qt5.1.1\5.1.1\msvc2012_64;C:\local\boost_1_65_1 -DBOOST_LIBRARYDIR=C:\local\boost_1_65_1\lib64 -DBOOST_INCLUDEDIR=C:\local\boost_1_65_1\boost -DBOOST_ROOT=C:\local\boost_1_65_1 -G "Visual Studio 11 2012 Win64" -DLSL_ROOT=..\..\LSL\liblsl\Release

However, I am getting the error that LSLAppBoilerPlate can not be loaded. I tried changing line 16 in the CMakeLists file to use the relative and absolute path to the boilerplate file with no success. I'm not quite sure what to do about that yet, more reading about cmake, I guess.

I suspect though that there will also be a problem with my -DLSL_ROOT variable, since I don't have an LSLConfig.cmake file.

**Comment by tstenner** [comment]
On Windows, the Qt location has to be set manually (unless the path is set in the environment variable or `cmake/LSLSaneDefaults.cmake` correctly guesses the path). For the [Windows CI](https://ci.appveyor.com/project/tstenner/labstreaminglayer/build/1.40.54#13) I set it manually and LSL+LabRecorder compiles correctly.
With the changes in 4b52ebf82c16d074, setting `LSL_ROOT` to the labstreaminglayer root directory yields a much better error message and links to the documentation.

**Comment by tstenner** [comment]
The naming for `LSL_ROOT` is too ambiguous. If nobody's opposed to it, I'll rename it to `LSL_INSTALL_ROOT` so it's explicit it doesn't mean the repository root.

**Comment by dmedine** [comment]
What I would find useful is to know how to simply feed cmake all the arguments regarding paths that it needs to find all necessary headers and libraries for the project generation. I'm getting there, but not yet finished. Then I will play around with this a bit and probably suggest some changes. 

My goal is to provide functioning cmake files for every 'important' C++ app. Then it's on to appveyor. Once this is done, I will be able to easily fill out the rest of the apps as people request updates. I don't see any reason to devote time to apps that people aren't using. But, it would be very useful, and indeed important as I don't find the SCCN ftp server at all reliable against the test of time, to have this solution.

Also, while I'm on the subject, there are still a couple of (tiny) tweaks I would like to make in the library cmake files, but these are very entirely superficial and I'll do a PR when I get around to it and we can discuss. As for now, this part is working just great.

**Comment by dmedine** [comment]
Comment on the previous from tstenner, yes.

**Comment by tstenner** [comment]
On the Windows machines, I've had the best experience with a single in tree build and `-DQt5_DIR` to find Qt5 and `-DBOOST_ROOT` to find Boost.
To find the compiler, I use either `-G "Visual Studio XYZ"` and let CMake work its magic or start it from the VC native shell and use `-G Ninja`. The newer Visual Studio versions also support opening a `CMakeLists.txt` and set the compilers according to a dropdown menu (even with 32 and 64 bit builds in a single workspace).

**Comment by dmedine** [comment]
I'm having much more success running from in the tree. I got a clean copy of master, ran CMake from the top and it 'just worked'. It seems that by bypassing CMakeLists.txt in the top directory and proceeding straight to the one in LSL/liblsl breaks the whole machinery. 

However, when trying to build LabRecorder out of tree, I am still thwarted by LSLAppBoilerPlate. I have tried everything I can think of to make CMake see this file, but it refuses to listen.

**Comment by dmedine** [comment]
The problem with LSLAppBoilerPlate has to do with the setting of LSL_ROOT (soon to be LSL_INSTALL_ROOT). When I run CMake from LabRecorder, it complains if LSL_ROOT is _not_ labstreaminglayer\build\install\lsl_Release\LSL\cmake. But, the cmakelists file there appends ${LSL_ROOT}\cmake to the module search path. I changed the append to just ${LSL_ROOT} and now the boilerplate is found.

Just one comment, I find it confusing that there is not a folder called 'install' in labstreaminglayer. Why is it 'hidden' inside build? This through me off a bit. I think that if we have a variable called LSL_INSTALL_ROOT, it should be apparent what this folder is. I had to hunt for the correct path for this variable. (We could also just be more explicit about this in the instructions.)

**Comment by tstenner** [comment]
Relative paths are problematic, but absolute paths work fine. Prefixing `LSL_ROOT` with either the current build directory or the source directory would break absolute paths and I think it would lead to more confusion.
As for the install folder I'm unsure where to put it. Some people might have 4 install folders (32/64 * Debug/Release) and I think Visual Studio doesn't change the install path when switching between 32/64 and Debug/Release builds, but then again it's easier to just install to `/install` so the common case (one architecture Release builds) is easier.

**Comment by dmedine** [comment]
Found another gotcha: my version of cmake apparently got released prior to boost 1.65.1, which is what I am trying to link against. I had to add it to the list of available boost versions in the file FindBoost.cmake (on my computer I find this file C:\local\boost_1_65_1\lib64 and the offending line is 1001).

But, I still can't get it to go. It insists on looking for the boost's static libraries, which I don't have. I have inserted set(Boost_USE_STATIC_LIBS OFF) all over the place in the code, but to no avail. I am printing the FindBoost debug info and it always reports this variable as being ON. WTF!??

**Comment by dmedine** [comment]
I take it back. I do have the static libs, but somehow FindBoost.cmake still can't find them. However, I am disconcerted that I can't flip the switch on that variable.

**Comment by dmedine** [comment]
This may just be a FindBoost issue.

**Comment by dmedine** [comment]
Actually, it is a dmedine issue, I was neglecting to tell cmake to make a project against vs2012 so it defaulted to msvc14, not 11, which is what I have.

Still, I got errors:
  Imported targets not available for Boost version 106501
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.9/Modules/FindBoost.cmake:871 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.9/Modules/FindBoost.cmake:1501 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:61 (find_package)

```

-- Looking for C++ include pthread.h
CMake Error at C:/Users/David.Medine/clean_lsl/labstreaminglayer/Apps/LabRecorder/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (set):
  Syntax error in cmake code at

    C:/Users/David.Medine/clean_lsl/labstreaminglayer/Apps/LabRecorder/CMakeFiles/CMakeTmp/CMakeLists.txt:2

  when parsing string

    C:\Users\David.Medine\clean_lsl\labstreaminglayer\build\install\lsl_Release\LSL\cmake

  Invalid character escape '\U'.
```

Then, I ran this:

`C:\Users\David.Medine\clean_lsl\labstreaminglayer\Apps\LabRecorder>cmake -DCMAKE_PREFIX_PATH=C:\Qt-VS2012_x64\Qt5.1.1\5.1.1\msvc2012_64 -DBOOST_LIBRARYDIR=C:\local\boost_1_65_1\lib64 -DBOOST_INCLUDEDIR=C:\local\boost_1_65_1\boost -DBOOST_ROOT=C:\local\boost_1_65_1 -DLSL_ROOT=C:\Users\David.Medine\clean_lsl\labstreaminglayer\build\install\lsl_Release\LSL\cmake -G "Visual Studio 11 2012 Win64"
`
a second time and it suceeded in building a project, but still issued a number of boost related errors (just a few are shown here):
```
CMake Error at CMakeLists.txt:49 (add_executable):
  Target "LabRecorder" links to target "Boost::iostreams" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at CMakeLists.txt:49 (add_executable):
  Target "LabRecorder" links to target "Boost::thread" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:49 (add_executable):
  Target "LabRecorder" links to target "Boost::zlib" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


-- Generating done
-- Build files have been written to: C:/Users/David.Medine/clean_lsl/labstreaminglayer/Apps/LabRecorder
```

The include directories for boost libraries are missing from the project, as is the Custom Build Tool properties for mainwindow.h and mainwindow.ui which call MOC and UIC respectively. These properties also need to somehow get shoved into the project by CMake.

**Comment by tstenner** [comment]
Instead of backslashes (which you'd need to escape, so `C:\foo\bar` becomes `C:\\foo\\bar`) I'd used forward slashes (accepted by every operating system). `Imported targets not available for Boost version 106501` means that Boost was found, but CMake doesn't automatically create the targets `Boost::iostreams` etc. You couuld either use a newer CMake version or an older Boost version ([see here](https://stackoverflow.com/questions/42123509/))

**Comment by dmedine** [comment]
Updating cmake did the trick. The only thing left is to create the custom build tools. By the way, the backslash issue shouldn't matter here because I am making the call from the command prompt. Also, I don't get any headaches from using relative paths. Not sure why.

**Comment by dmedine** [comment]
Alright, I'm almost there with the outoftree single app build on Windows. The last thing is the packaging. When I build from the command line, it 'installs' the app in C:\Program Files\LabRecorder\LabRecorder. Obviously this requires admin access. It should install to a local directory, and my understanding is that this is what is intended by the environment. 

Also, the executable still doesn't run. It needs to have (as I mentioned above) a directory called platform containing qwindows.dll (from qt's plugins/platforms folder --- which, I noticed, also comes with my CMake installation), or that folder needs to be on the path (which we don't want).

**Comment by cboulay** [comment]
The install directory is controlled by `CMAKE_INSTALL_PREFIX`, which defaults to C:/Program Files/ unless specified. We can provide our own default if it's not set at the command line.

Where would you like out-of-tree single app builds to 'install' the binaries? Next to the LSL library binaries, or within the directory containing the to-be-built app?

**Comment by tstenner** [comment]
What's the main motivation to build apps out of tree?

**Comment by cboulay** [comment]
I'm not sure, but I guess it makes it possible to provide a minimal 'Learn2LSL' environment where all you have to do is give the student working binaries and minimal configs in a read-only directory, then they can make their own MyFirstCApp in their own dir.

**Comment by cboulay** [comment]
About LSL_ROOT, I just ran into a few usability issues, some the same as @dmedine .

In INSTALL.md, the instructions are to use cmake-gui and configure some variables in the GUI itself. I thought I would keep this workflow and do the out-of-tree build the same but I couldn't because it error'd out on lack of LSL_ROOT. I think we should modify the apps check for LSL_ROOT to simply not configure any targets anything if the variable is missing, but then it can be set after and a subsequent reconfigure will create the target.

So then I moved on to trying from the command line and ran into one of the errors David did regarding the backslash vs forward slash. I like to use file explorer to find the directory I'm looking for, highlight the address bar, copy, then go to my command prompt and type `"`, right-click, `"`. This USUALLY works. The problem here is that we are asking the user to provide a parent directory and then our cmake code is  appending a `/cmake` to that string. I guess cmake doesn't know how to handle mixed file separators. So we can either ask the user to provide the full path (including \cmake at the end) or we can use a `file(TO_CMAKE_PATH ${LSL_ROOT} LSL_ROOT)` before appending the \cmake.

I don't want to make these changes on master because I don't know what all has changed in tstenner/lslboost_update (which I think you are both working from currently). Let me know when things settle and if you want me to make these changes if it hasn't been fixed already.

**Comment by cboulay** [comment]
Just remembered another. While using cmake-gui to configure only liblsl, I received a warning that Qt5_DIR was guessed at. Probably LSLSaneDefaults.cmake Qt5_DIR part shouldn't be called unless attempting to configure an app that requires Qt.

**Comment by cboulay** [comment]
@dmedine If you have write access to the install directory, then building the INSTALL target should automatically take care of all the Qt plugins for you. I created a `build` folder as a child of the LabRecorder folder, changed into it, then ran the following command...

`cmake .. -DLSL_ROOT="E:/SachsLab/Tools/Neurophys/labstreaminglayer/build/install/lsl_Release/LSL" -DQt5_DIR="C:\Qt\5.9.1\msvc2015_64\lib\cmake\Qt5" -DBOOST_ROOT=C:\local\boost_1_65_0 -G "Visual Studio 14 2015 Win64" -DCMAKE_INSTALL_PREFIX=./`

Then I built the LabRecorder target then the INSTALL target. Inside my build/LabRecorder directory was the executable and all its dependencies.

**Comment by tstenner** [comment]
@cboulay Good idea with TO_CMAKE_PATH. If you want, you can take #244 and change it, otherwise I'll do it next week

**Comment by cboulay** [comment]
I don't think I can get to this any earlier than you can, so it's probably better that you do it. Sorry, and thank you.

**Comment by dmedine** [comment]
@tstenner I think it is important to be able to build apps one at a time (i.e. out of tree). Also, I still haven't succeeded in using this cmake environment to build a working app at all. I should probably understand how to do this :)

**Comment by dmedine** [comment]
@cboulay using your method above I still don't get the qt libraries copied into the folder. I get the same error message I describe above. Is it possible that there some global variable that gets set on your system to point to these libraries (specifically qwindows.dll)?

**Comment by dmedine** [comment]
I simply cannot make this work. I had to make some changes to the boilerplate code (I am using MSVC11, which is left out of the if statement here: https://github.com/sccn/labstreaminglayer/blob/master/cmake/LSLAppBoilerplate.cmake#L105-L113) in order to make it call winqtdeploy, which I assume is what should do the job of packaging up the necessary binaries with the executable, but it still doesn't work. 

And, the error message is still the same.

When I try generate the projects 'intree' I use the following command:`
cmake -DCMAKE_PREFIX_PATH=C:\Qt-VS2012_x64\Qt5.1.1\5.1.1\msvc2012_64 -DBOOST_LIBRARYDIR=C:\local\boost_1_65_1\lib64 -DBOOST_INCLUDEDIR=C:\local\boost_1_65_1\boost -DBOOST_ROOT=C:\local\boost_1_65_1 -DLSL_INSTALL_ROOT=C:\Users\David.Medine\clean_lsl\labstreaminglayer\build\install\lsl_Release\LSL\ -G "Visual Studio 11 2012 Win64"` 

But, when it comes time to building LabRecorder, I get errors:
```
c:\users\david.medine\clean_lsl\labstreaminglayer\apps\labrecorder\recording.h(11): fatal error C1083: Cannot open in
clude file: 'boost/thread.hpp': No such file or directory [C:\Users\David.Medine\clean_lsl\labstreaminglayer\Apps\LabRe
corder\LabRecorder.vcxproj]
```

Not sure why the include directories are false when running intree.

**Comment by cboulay** [comment]
That command isn't for an 'in tree' build. An 'in tree' build would almost certainly use `labstreaminglayer\build` as the working directory, pass `..` as your cmake target, it would be necessary to add `-DLSLAPPS_LabRecorder=ON` and you shouldn't add `LSL_INSTALL_ROOT`. Then your generated project would have both liblsl and LabRecorder targets.

But the above out of tree build should work.

One point before we continue: it's generally a bad idea to run cmake 'in source'. cmake creates a bunch of intermediate files that can interfere with future attempts to run cmake if they aren't cleaned out first. It's hard to clean them out if they are mixed in with your source files. For this reason, it's almost universally true that you should create a `build` directory, `cd` into that, then call cmake with `..` as the location of the CMakeLists.txt file. If anything goes wrong then this build directory can be easily deleted (`cd ..` and `rmdir /S build` in command prompt) then you can try again (`mkdir build && cd build`). We also add `build` to the .gitignore files so you don't have to worry about your cmake config files getting added to git.

I think you'll have to clean your LabRecorder directory of any cmake cache files before we can try to diagnose your problem.

One more note: I usually don't have to supply `BOOST_LIBRARYDIR` and `BOOST_INCLUDEDIR` if `BOOST_ROOT` is correct and the whole boost directory structure is correct. If you're finding that you need to supply those then either your boost directory doesn't match the structure generated using the installer (e.g., you built boost yourself) or your cmake config is messed up somewhere.

**Comment by dmedine** [comment]
Thanks for the tips, Chadwick. making a build directory and running cmake from there automatically solved a lot of problems. 

However, I'm still getting the runtime error when I run LabRecorder and copying the qwindows dll into the exe's directory still doesn't help.

**Comment by tstenner** [comment]
Is there a subfolder `platforms` in the LabRecorder directory? Qt will search there for the qwindows.dll but (I think) not in the same folder.

**Comment by dmedine** [comment]
No. And even if I put one there by hand it doesn't work.

**Comment by tstenner** [comment]
Does [this build](https://bintray.com/tstenner/labstreaminglayer/download_file?file_path=LabRecorder.7z) work?

**Comment by cboulay** [comment]
It's possible that your particular mix of qt and msvc have a problem with windeployqt. I'm now downloading the same versions as you and I'll give it a go.

**Comment by cboulay** [comment]
Here is my cmake command (in tree build): 
`labstreaminglayer\build_msvc11>cmake .. -DQt5_DIR="C:\Qt\5.1.1\msvc2012_64\lib\cmake\Qt5" -DBOOST_ROOT="C:\local\boost_1_65_1" -DLSLAPPS_LabRecorder=ON -G "Visual Studio 11 2012 Win64" -DCMAKE_INSTALL_PREFIX=./install`

And so far I've found that `QT_DEPLOYQT_EXECUTABLE-NOTFOUND`. Looking in C:\Qt\5.1.1\msvc2012_64\bin, I see that in fact there is no windeployqt.exe. So I guess we don't support Qt 5.1.1?

**Comment by cboulay** [comment]
I just tried with Qt5.2.1 and the windeployqt tools is good enough (for LabRecorder at least). However, it does not support the `--no-opengl-sw --no-compiler-runtime` arguments.

Options:

1. Do not use these arguments, thus adding support for Qt5.2.1 and VS2012.
2. Use these options and limit support to Qt >= 5.3 and VS >= 2013.

**Comment by cboulay** [comment]
Removing those options leads to the deploy tool adding vcredist_x64.exe at 15MB and opengl32sw.dll at 20MB to every app directory.

By the way, whether or not those options are in, versions of Qt pre 5.5 (I think) will package the ICU dlls, and those are >= 20 MB.

So, @dmedine , how badly do you need VS2012 supported?

**Comment by dmedine** [comment]
Good thinking @cboulay! It didn't occur to me that the version of qt5. This is my first time with cmake and while it seems to have all the answers for open-source cross platform projects, I find the errors and error reporting not particularly meaningful. But, maybe that's just a newb's take on it.

To answer your question, I don't need any particular set of tools supported, I am just trying to poke holes in this thing---which I've seemed to have succeeded at :). 

With an eye to the future, I do want to have the apps deployable through appveyor as well. I don't see anything wrong with keeping things up to date with dependencies and tools. But, I do want to preserve the feature that the apps are usable out of the box. I haven't started to explore appveyor etc. yet, so I don't know if that is even possible; i.e. that one won't have to rely on having qt and boost set up in some particular way just to run the app. Maybe you or tstenner already knows the answer to that.

So, yes, let us only support qt>=5.3 and msvc>=2013. Although, the opengl thing probably doesn't make much of a difference. I would imagine that is only meaningful in the context of moving images.

**Comment by tstenner** [comment]
Shoot, just as I've finished setting VS2008 up on AppVeyor

**Comment by cboulay** [comment]
It was in an edit so you probably missed it, but I added support for 5.2.1 by checking for the qmake version and then omitting qtwindeploy arguments if less than 5.3.0. So we now support VS2012 and Qt 5.2.1.

If we want to support using the cmake build system to build qt-enabled Apps using MSVC older than 2012, then we'll need to manually copy the requisite dlls. That seems like a lot of work for no payoff. Those users that are somehow limited to running MSVC older than 2012 will simply have to ask us for precompiled binaries or build the app on a different system, or build the app on their own using their own hand-tuned projects.

**Comment by dmedine** [comment]
Yeah, we can just ditch the older stuff as far as I'm concerned.

**Comment by dmedine** [comment]
So now it does do the windeplayqt stuff, but the exe still throws the runtime error when I try to start it. I'm using VS 2012 and Qt5.2.1 (64 bit). I will try with 32 bit and 2015 and newer versions of qt. Unfortunately my microsoft account is down and my IT department is on vacation so I don't have access to 2013.

**Comment by tstenner** [comment]
The oldest compiler AppVeyor offers is VS2008, but the Qt supports only starts with VS2013 ([source](https://www.appveyor.com/docs/build-environment/#qt)), so I'd be in favor of removing support for compiling Apps with VS2012.

**Comment by dmedine** [comment]
Yes, absolutely. I can't think of any reason at all to support older IDEs for the Apps.

**Comment by dmedine** [comment]
Finally made this work: https://github.com/sccn/labstreaminglayer/pull/249

**Comment by dmedine** [comment]
I just checked out a fresh clone of the source and ran the cmake command:
`cmake ../ -DQt5_DIR=C:\Qt\Qt5.9.2\5.9.2\msvc2017_64\lib\cmake\Qt5 -DBOOST_ROOT=C:\local\boost_1_65_1 -DBOOST_LIBRARYDIR=C:\local\boost_1_65_1\lib64-msvc-14 -DBOOST_INCLUDEDIR=C:\local\boost_1_65_1\boost -DLSL_INSTALL_ROOT=C:\Users\David.Medine\clean_lsl\labstreaminglayer\build\install\lsl_Release\LSL -DLSLAPPS_VideoRecorder=ON -G "Visual Studio 14 2015 Win64"`

Followed by the build command:
`cmake --build . --config Release --target install`

liblsl and LabRecorder build without error, but LabRecorder.exe will not run. It complains that it is missing liblsl64.dll. When I copy the library into the folder I get further entry point/qt related errors.

Here is the terminal output: https://pastebin.com/u4TADLCr

I don't know why this is now broken. I did move to Qt5.9.2, but it appears to be correctly configured. Also, poking through the changes to the repository in the last few days I don't see anything that should have caused this to happen.

**Comment by dmedine** [comment]
Doh! Yeah that was the problem. I think that I may have finally made every mistake possible in using this thing, so I should be set now. Thanks for holding my hand through this.

**Comment by dmedine** [comment]
One more question @tstenner. I am developing a new app. How do I do the cmake dance so that I can actually debug the target? If I do the normal steps, the target gets installed to the install directory where the MSVC debugger can't get at it? You're working on the BrainAmp app, right, so you must be doing this on Windows, right?

**Comment by cboulay** [comment]
@dmedine , in your previous post, was it necessary to provide the `BOOST_LIBRARYDIR` and `BOOST_INCLUDEDIR`, or would configure and build still work without them? We'd like for those arguments to not be necessary.

Also `LSL_INSTALL_ROOT` should not be necessary if you are using the default, which it seems you are.

And to answer your most recent question, it's not necessary to call `cmake --build`. The first cmake command generates a Visual Studio project file which you can simply double-click on and enter into the IDE as you would with hand-tuned project files. Once in the IDE, you can debug your target as usual, except you'll probably have to manually add any DLLs that aren't on the path to the folder where VS keeps the (built but not installed) Debug\App.exe.

I think it is possible to get cmake to generate build rules to copy over the required DLLs automatically into the temporary build directories but this is quite a bit more complicated than doing it for install targets. I think that most developers who are debugging with MSVC on Windows should already be in the first or second circle of DLL-Hell, and the small ask to get them to copy some more DLLs is a lot less work than getting cmake to do it for us.

**Comment by cboulay** [comment]
I just noticed that you are using a generator for MSVC 2015 but you are pointing Qt5Dir to Qt for msvc2017. I would expect this to cause problems.

**Comment by dmedine** [comment]
> @dmedine <https://github.com/dmedine> , in your previous post, was it 
> necessary to provide the |BOOST_LIBRARYDIR| and |BOOST_INCLUDEDIR|, or 
> would configure and build still work without them? We'd like for those 
> arguments to not be necessary.
>
It appears that those are no longer necessary for in tree builds. The 
sneaky anaconda-out-of-date cmake install that I was ignorantly calling 
(I think it was 3.6 as opposed to 3.9) was the culprit there.
>
> Also |LSL_INSTALL_ROOT| should not be necessary if you are using the 
> default, which it seems you are.
>
Yes. I've removed that as well. That line gets bashed out anyway if it 
is in tree.
>
> And to answer your most recent question, it's not necessary to call 
> |cmake --build|. The first cmake command generates a Visual Studio 
> project file which you can simply double-click on and enter into the 
> IDE as you would with hand-tuned project files. Once in the IDE, you 
> can debug your target as usual, except you'll probably have to 
> manually add any DLLs that aren't on the path to the folder where VS 
> keeps the (built but not installed) Debug\App.exe.
>
This is precisely what I'm trying to avoid. I would prefer it if I could 
generate a project file that was development ready.
>
> I think it is possible to get cmake to generate build rules to copy 
> over the required DLLs automatically into the temporary build 
> directories but this is quite a bit more complicated than doing it for 
> install targets. I think that most developers who are debugging with 
> MSVC on Windows should already be in the first or second circle of 
> DLL-Hell, and the small ask to get them to copy some more DLLs is a 
> lot less work than getting cmake to do it for us.
>
Yes. I have spent the last hour or so trying to do exactly this and I am 
getting nowhere. Considering the rather slow pace of new apps, this 
probably isn't worth the effort. Even with some manual copying cmake is 
still faster than making a new project file by hand or adapting an old 
one. Still, it feels a little sloppy.

Also the msvc_2017 thing was a typo in my last post.

**Comment by cboulay** [comment]
In case anyone wants to tackle this, here are a couple resources.
[1](https://stackoverflow.com/questions/21971189/how-to-debug-cmake-target-after-install)
[2](https://stackoverflow.com/questions/1005901/how-to-set-path-environment-variable-using-cmake-and-visual-studio-to-run-test/1307784#1307784)

And apparently VS2017 has the ability to debug install targets but I haven't investigated further.

**Comment by tstenner** [comment]
I've debugged / profiled code with MSVC before so it's definitely possible, I don't know how I did it exactly. In the worst case scenario it's still possible to attach the debugger to a running process, in the best case it's just an rpath setting

**Comment by tstenner** [comment]
I checked how I did it and it's quite comfortable with the native CMake functionality @cboulay mentioned. Visual Studio knows all your targets and offers to debug executables either in the build folder or install folder.
