### ISSUE TITLE
Lab recorder does not recognize stream

### ISSUE THREAD

**Issue by noanutke** [sccn/lsl_archived#254]
Hi,

I have the following problem:
I have 2 programs: p1 and p2. p1 is written in python and p2 is written in unity. 
When running p1 on computer "A", computer "B" that is on the same local network as computer "A" and has the lab recorder on it, recognizes the stream and works well. However, when running p2 (the unity program) on computer "A", then the lab recorder on computer "B" doesn't recognize any stream.

Note, that when running lab recorder and p2 **on the same computer,** the lab recorder works well and records the data.

Any idea what might be the problem? Any setting I might me missing for the Unity program (p2)?

thanks!

**Comment by dmedine** [comment]
Are you sure Windows' firewall is off?

**Comment by noanutke** [comment]
Is there a chance it is on, if for the same computers it works for a python program?

**Comment by dmedine** [comment]
Ahh. I didn't understand your question. I would verify that the unity stream is truly streaming. If there is a live stream on the network, LabRecorder will see it. Since it sees p1, there is a good connection. Thus, there must be something wrong with p2.

**Comment by noanutke** [comment]
Thanks, but did you notice that p2 works well when the lab recorder and p2 are on the same computer? Doesn't it mean that the stream is indeed streaming?

**Comment by cboulay** [comment]
@noanutke Sorry for not seeing this earlier. Do you use [LSL4Unity](https://github.com/xfleckx/LSL4Unity)? I've used that to generate a stream on A and record in LabRecorder on B.

Actually I don't use most of the convenience scripts provided by LSL4Unity... I just use the basic LSL.cs. LSL4Unity is convenient because it's easy to import as a package and because it comes with new binaries (compiled by me).

**Comment by cboulay** [comment]
The solution is probably in the Wiki.
https://github.com/sccn/labstreaminglayer/wiki/NetworkConnectivity
(if the link is no longer valid then please search the docs folder).

There hasn't been any activity on this issue for a year so I'm closing. If you need to re-open, please do so at github.com/labstreaminglayer/App-LabRecorder
