### ISSUE TITLE
Firewall settings for LSL to work?

### ISSUE THREAD

**Issue by HWiese1980** [sccn/lsl_archived#362]
Hey everyone,

what are common firewall settings to make LSL run? I have a wifi network here which has some certain limitations like only allowing git, svn, https and some other protocols. How can I make LSL work with this layer of security?

Thanks

**Comment by mgrivich** [comment]
The easiest approach is to shut the firewall off on all relevant 
computers and networks. If that is not allowed, you can open the default 
ports:

The features that are required by LSL to work in its default settings 
are UDP broadcasts or multi-cast on port 16571, as well as incoming TCP 
and UDP connections on ports 16572-16604 (although the upper ranges are 
only needed if you have sufficiently many LSL applications open on a 
single machine).

If you are not allowed to open ports, you have to reconfigure LSL to use 
ports that are available: 
https://github.com/sccn/labstreaminglayer/wiki/NetworkConnectivity.wiki 
-> Configuration File Contents.

Personally, though, before messing with this I'd probably set up a 
personal network and neglect to mention it to your IT department. 
Ubiquiti networks work well, though they can be a bit challenging to set 
up. https://www.youtube.com/watch?v=f7FeYsJqotc gets you 90% of the way 
there.

**Comment by HWiese1980** [comment]
Thank you!
