### ISSUE TITLE
Errors when building BrainAmp App

### ISSUE THREAD

**Issue by tnguyen1992** [sccn/lsl_archived#364]
Hi, 
I am currently setting up LSL on our Windows 10 PC with all the configurations and environments installed, but when I try to generate the Install files in Cmake this error comes up (I am currently setting up Labrecorder and the brainamp interface):

CMake Error in Apps/LabRecorder/CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   C:/Users/User/Documents/labstreaminglayer/build/Apps/LabRecorder/LabRecorder_path

CMake Error in Apps/LabRecorder/CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   C:/Users/User/Documents/labstreaminglayer/build/Apps/LabRecorder/LabRecorder_path

CMake Error in Apps/BrainAmpSeries/CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   C:/Users/User/Documents/labstreaminglayer/build/Apps/BrainAmpSeries/BrainAmpSeries_path

CMake Error in Apps/BrainAmpSeries/CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   C:/Users/User/Documents/labstreaminglayer/build/Apps/BrainAmpSeries/BrainAmpSeries_path

CMake Error in Apps/BrainProducts/BrainVisionRDA/CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   C:/Users/User/Documents/labstreaminglayer/build/Apps/BrainProducts/BrainVisionRDA/BrainVisionRDA_path

CMake Error in Apps/BrainProducts/BrainVisionRDA/CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   C:/Users/User/Documents/labstreaminglayer/build/Apps/BrainProducts/BrainVisionRDA/BrainVisionRDA_path

Can anybody help me with that?

Cheers, 
Trinh

**Comment by cboulay** [comment]
Please post this issue at github.com/sccn/labstreaminglayer
Please provide a detailed description of exactly what instructions you followed starting from an empty folder to getting these messages.
For bonus points, please encapsulate the copy-pasted text in a code block (triple back-tick) to make it easier to read.

This archived repository is only for historical purposes and in case we need to track any OLD issues. No NEW issues are allowed.
