### ISSUE TITLE
BrainVisionRDA: compilation error (CMake on Windows) 

### ISSUE THREAD

**Issue by OscarBedford** [sccn/lsl_archived#366]
We are trying to install labstreaming layer and enable specific apps following the guidelines in:

https://github.com/sccn/labstreaminglayer/wiki/INSTALL

It seems to configure correctly using:

cmake C:\labstreaminglayer -G "Visual Studio 15 2017 Win64" -DLSL_LSLBOOST_PATH=C:\labstreaminglayer\LSL\liblsl\lslboost -DQt5_DIR=C:\Qt\5.12.3\msvc2017_64\lib\cmake\Qt5 -DBOOST_ROOT=C:\boost_1_67_0\stage\lib -DLSLAPPS_LabRecorder=ON -DLSLAPPS_XDFBrowser=ON -DLSLAPPS_Examples=ON -DLSLAPPS_Benchmarks=ON -DLSLAPPS_BestPracticesGUI=ON -DLSLAPPS_BrainVisionRDA=ON -DBoost_INCLUDE_DIR=C:\boost_1_67_0

We then run this specific command to install the previously enabled apps:

cmake  --build C:\labstreaminglayer\build --config Release --target C:\labstreaminglayer\build\install

Although Labrecorder installs properly, the following error results when it tries to build BrainVisionRDA:

C:\labstreaminglayer\Apps\BrainProducts\BrainVisionRDA\mainwindow.cpp(194): error C2679: binary '=': no operator found which takes a right-hand operand of type 'boost::asio::ip::tcp::endpoint' (or the
re is no acceptable conversion) [C:\labstreaminglayer\build\Apps\BrainProducts\BrainVisionRDA\BrainVisionRDA.vcxproj]
  C:\boost_1_67_0\boost/asio/ip/basic_resolver_iterator.hpp(103): note: could be 'boost::asio::ip::basic_resolver_iterator<InternetProtocol> &boost::asio::ip::basic_resolver_iterator<InternetProtocol>
  ::operator =(boost::asio::ip::basic_resolver_iterator<InternetProtocol> &&)'
          with
          [
              InternetProtocol=boost::asio::ip::tcp
          ]
  C:\boost_1_67_0\boost/asio/ip/basic_resolver_iterator.hpp(94): note: or       'boost::asio::ip::basic_resolver_iterator<InternetProtocol> &boost::asio::ip::basic_resolver_iterator<InternetProtocol>:
  :operator =(const boost::asio::ip::basic_resolver_iterator<InternetProtocol> &)'
          with
          [
              InternetProtocol=boost::asio::ip::tcp
          ]
  C:\labstreaminglayer\Apps\BrainProducts\BrainVisionRDA\mainwindow.cpp(194): note: while trying to match the argument list '(boost::asio::ip::basic_resolver_iterator<InternetProtocol>, boost::asio::i
  p::tcp::endpoint)'
          with
          [
              InternetProtocol=boost::asio::ip::tcp
          ]

**Comment by cboulay** [comment]
Hi, a few things.

* This repo is around for historical purposes. I can't remember why it isn't set to 'archived' in GitHub to prevent people from posting issues, but I think there was a reason at one point. In any case, I'm going to close this issue and ask you open an issue in the appropriate repository if my answer below doesn't help.

* The docs are mostly moved to readthedocs: https://labstreaminglayer.readthedocs.io/
Along with a move to readthedocs is a general change in our philosophy: Try to download the releases first. If they don't exist then ask. If they don't work for you then let us know.

* The first place to look for releases is in each repository's 'releases' page. I think what you want can be found here: https://github.com/labstreaminglayer/App-BrainProducts/releases

* If you really want to build the application yourself, follow these instructions: https://labstreaminglayer.readthedocs.io/dev/app_build.html

**Comment by dmedine** [comment]
Yes. Chad is correct. Please post issues to the contemporary issues page.

In the meantime, you can download a fresh (windows) release of the RDA
connector here:
https://github.com/brain-products/LSL-BrainVisionRDA/releases
