### ISSUE TITLE
blocking call to pull_sample become unresponsive when no data available

### ISSUE THREAD

**Issue by balandongiv** [sccn/lsl_archived#368]
**Setting**:
In the `pull_sample` function, the timeout was set to 1 second.
Then, deliberately let no data stream coming from the sensor.

**Expected**:
The `pull_sample` function should _**return**_ to the calling function whenever the time limit (1 second) is exceeded should there are no data available in the `open_stream `que.

**Problem**:

The application stuck infinitely in the `lsl_pull_sample_d `function despite the timeout  (1 second) has exceeded.

**Question**
  Either I mistakenly understand the role of the timeout var or there is something that I am missing in the **sccn** setup?  Is there any ways to return to the calling function whenever there is no available data upon certain period of time?

Appreciate for any help to address this problem.

**Comment by balandongiv** [comment]
Download the latest build solved the problem.

**Comment by balandongiv** [comment]
Apparently, even with the latest download from Github repo, the `timeout` capability is not working with MATLAB 2019a and MATLAB 2020a

**Comment by cboulay** [comment]
This is the incorrect repository. You already opened the issue in the correct repository.
