### ISSUE TITLE
new ios-devel branch notes

### ISSUE THREAD

**Issue by dmedine** [sccn/lsl_archived#57]
I have made a new branch on git called 'ios-devel'. This has a new folder in the LSL directory with a couple of xcode projects in it. One builds liblsl into an iOS framework. The other is a helloworld app to test lsl.
1. For this to work I had to compile boost into an iOS archive. I did this a long time ago, and I can't find out how I did it, but I think I used this method:
   https://github.com/danoli3/ofxiOSBoost
   Unfortunately, I seem to have misplaced the folder with this project in it. I might be able to track it down eventually, but for now, there is a libboost.a file that works.
2. In order to compile this for iOS 8, I had to modify pugixml.hpp slightly. I commented out line 22:
   struct bidirectional_iterator_tag;
   This makes me realize that we are shipping LSL with a pretty old version of pugixml. We've got 1.0 and I believe they are up to 1.6. After a quick glance at 1.6, I see that the offending line is nowhere to be found, but the whole header looks a lot different. As a side note, it might be worth while to try LSL with the latest version of pugixml.
3. The example program for iOS, 'lsl-helloworld', functions correctly as far as sending and receiving lsl streams, but the part of the code that listens to LSL streams and prints them to a sort  of 'console' that I created has a memory leak in it. Perhaps someone with better app development chops than I have can make this more functional. This was my first time in the ring with objective-C.

**Comment by chkothe** [comment]
Cool!

Re pugixml, we should read through the change log if there's any critical
bugfix, and whether they tend to break things and then fix them in later
releases (in that case I'd be careful about the upgrade).

Christian
