### ISSUE TITLE
chunk of data equal to sample rate in Matlab

### ISSUE THREAD

**Issue by akshaybabloo** [sccn/lsl_archived#67]
Hi,

I have been trying to get chunk of data on every call to LSL for Cognionics.

I tried using doing something like this

```
for s = 1:500
    test(s,:) = vec
end
```

But this repeats the data.

where the sample rate is 500. Cant I get a data in chunks of the sample rate? like `[sample_rate x number_of_channels]`?

Thanks.

**Comment by chkothe** [comment]
When you set up your inlet you can set the desired chunk size in seconds in
the construction parameters, so you need to set that to 1.

**Comment by akshaybabloo** [comment]
Is that at https://github.com/sccn/labstreaminglayer/blob/master/LSL/liblsl-Matlab/lsl_inlet.m#L43 `chunksize = 1`?

**Comment by chkothe** [comment]
Yes. The default value of 0 means "give me all new samples since last time
I asked".

**Comment by akshaybabloo** [comment]
Ok if the value is more than 0 or 1 would that mean that I want that many number of samples, like for example if I say chunksize = 500, I am getting 500 sample but some times I also get 1000?

**Comment by chkothe** [comment]
If you say chunksize=7 then you should be getting 7 seconds worth of data
every time (which is 3500 samples).

**Comment by akshaybabloo** [comment]
Thank you for the help.

**Comment by akshaybabloo** [comment]
I tried that but my output size is [35x37], and my sample rate was set to 300 which means I should be getting [300x37] per second. Do you have any idea how should I get it to output [300x37] per second?

**Comment by chkothe** [comment]
I forgot to mention that, while this parameter allows you to request a
desired chunk size, it's mostly meant to optimize throughput and it's
currently not guaranteed that you don't also get occasionally smaller
chunks. So, if you have a fixed-size buffer of a certain length that you
want to fill up and then operate on, you may have to perform that buffering
in your own script.
